-- Generated by HyprMod

-- Settings
hl.config({
    general = {
        allow_tearing = false,
        border_size = 2,
        col = {
            active_border = {
                colors = {"rgba(6bbf40ff)", "rgba(6bbf40ff)"},
                angle = 45,
            },
            inactive_border = "0xff5e5c64",
        },
        gaps_in = 10,
        gaps_out = 8,
        snap = {
            enabled = false,
        },
    },
})

-- Monitors
hl.monitor({
    output = "HDMI-A-1",
    disabled = false,
    mode = "3840x2160@60.00Hz",
    position = "20x0",
    scale = 1.5,
    transform = 3,
    cm = "srgb",
})
hl.monitor({
    output = "eDP-1",
    disabled = false,
    mode = "2560x1600@240.00Hz",
    position = "-1580x970",
    scale = 1.6,
    cm = "srgb",
})
