config_version = 14

[bar.default]
capsule_radius = 6
center = [ "audio_visualizer" ]
end = [ "tray", "spacer_1", "clock", "spacer_1", "notifications", "volume", "session" ]
font_family = "Monocraft"
start = [ "group:g1", "group:g2", "workspaces" ]

    [bar.default.dead_zone.actions]
    scroll_down = "volume-down"
    scroll_up = "volume-up"

    [[bar.default.capsule_group]]
    accordion = false
    accordion_direction = "end"
    border = ""
    enabled = true
    fill = "on_secondary"
    id = "g1"
    members = [ "temp", "sysmon_2", "sysmon_3" ]
    opacity = 1.0
    padding = 6.0

    [[bar.default.capsule_group]]
    accordion = true
    accordion_direction = "end"
    enabled = true
    fill = "outline"
    id = "g2"
    members = [ "wallpaper", "mpvpaper", "wallhaven" ]
    opacity = 1.0
    padding = 6.0

[brightness]
enable_ddcutil = true
sync_all_monitors = true

[hot_corners]
enabled = true

    [hot_corners.top_left]
    action = "command"
    command = "if wpctl get-volume @DEFAULT_AUDIO_SINK@ | grep -q MUTED && wpctl get-volume @DEFAULT_AUDIO_SOURCE@ | grep -q MUTED; then wpctl set-mute @DEFAULT_AUDIO_SINK@ 0; wpctl set-mute @DEFAULT_AUDIO_SOURCE@ 0; else wpctl set-mute @DEFAULT_AUDIO_SINK@ 1; wpctl set-mute @DEFAULT_AUDIO_SOURCE@ 1; fi"

[lockscreen]
enabled = false

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-2", "lockscreen-login-box@HDMI-A-1", "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 720.0
    cy = 2236.444580078125
    output = "HDMI-A-1"
    placement_height = 2560.0
    placement_width = 1440.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 800.0
    cy = 818.0
    output = "eDP-1"
    placement_height = 1000.0
    placement_width = 1600.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-2"]
    box_height = 196.0
    box_width = 810.0
    cx = 800.0
    cy = 818.0
    output = "eDP-2"
    placement_height = 1000.0
    placement_width = 1600.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-2".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[plugin_settings."noctalia/mpvpaper"]
video_directory = "/home/zxzx/视频/Wallpaper"

[plugins]
enabled = [ "noctalia/wallhaven", "noctalia/mpvpaper" ]

[services]
ddcutil = true

[shell]
avatar_path = "/home/zxzx/图片/face.jpg"
corner_radius_scale = 2.0
external_ip_enabled = true
font_family = "Monocraft"
screen_time_enabled = true

    [shell.animation]
    speed = 0.5000000074505806

    [shell.screen_corners]
    enabled = true

    [shell.screenshot]
    annotate = false
    copy_to_clipboard = false
    directory = "/home/zxzx/Sync/Screenshots"
    pipe_command = "swash \"$NOCTALIA_SCREENSHOT_PATH\""
    pipe_to_command = true
    save_to_file = true

[theme.templates]
builtin_ids = [ "btop", "gtk3", "gtk4", "kcolorscheme", "qt" ]

[wallpaper]
directory = "/home/zxzx/图片/Wallpaper"

    [wallpaper.default]
    path = "/home/zxzx/图片/Wallpaper/song_so_mi/ascii-4/songbird-compact-color.png"

    [wallpaper.last]
    path = "/home/zxzx/.cache/noctalia/mpvpaper/__static.jpg"

    [wallpaper.monitors.HDMI-A-1]
    path = "/home/zxzx/.cache/noctalia/mpvpaper/__static.jpg"

    [wallpaper.monitors.eDP-1]
    path = "/home/zxzx/.cache/noctalia/mpvpaper/__static.jpg"

    [wallpaper.monitors.eDP-2]
    path = "/home/zxzx/.cache/noctalia/mpvpaper/__static.jpg"

[weather]
enabled = false

[widget.active_window]
enabled = false

[widget.audio_visualizer]
bands = 128
show_when_idle = true
width = 650

[widget.clock]
format = "{:%H:%M  %m/%d/%y}"
tooltip_format = "Day %j Week %W %A"

[widget.media]
enabled = false

[widget.mpvpaper]
type = "noctalia/mpvpaper:mpvpaper"

[widget.sysmon_3]
label_show_units = false
show_glyph = false
visualization = "none"

[widget.tray]
capsule = false
hidden = [ "clash-verge" ]

[widget.wallhaven]
type = "noctalia/wallhaven:wallhaven"